service: jardim-inteligente-backend

provider:
  name: aws
  runtime: python3.8

package:
  individually: true
  include:
    - utils/*.py

custom:
  prune:
    automatic: true
    number: 3
  serverless-offline:
    host: 0.0.0.0

functions:
  - ${file(routes/user.yml)}

plugins:
  - serverless-offline
  - serverless-python-requirements
