service: jardim-inteligente-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221

custom:
  prune:
    automatic: true
    number: 3

functions:
  - ${file(routes/user.yml)}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-python-requirements